/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iamriven.joyeria;

/**
 *
 * @author Juan Antonio
 */
public class jPanel6Update extends javax.swing.JPanel {

    /**
     * Creates new form jPanel6Update
     */
    public jPanel6Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1NombreJoyeriaViejo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1ActualizarSinEncantar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1Viejo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1NombreJoyeria1Nuevo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2Nuevo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setName("updatesinencantar"); // NOI18N
        setPreferredSize(new java.awt.Dimension(722, 379));

        jTextField1NombreJoyeriaViejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NombreJoyeriaViejoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Actualizar joyeria sin encantar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre viejo");

        jButton1ActualizarSinEncantar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1ActualizarSinEncantar.setText("Actualizar");
        jButton1ActualizarSinEncantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActualizarSinEncantarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de joyeria");

        jComboBox1Viejo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Elegir tipo", "Anillo", "Pendiente", "Cinturon", "Colgante" }));
        jComboBox1Viejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ViejoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nombre nuevo");

        jTextField1NombreJoyeria1Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NombreJoyeria1NuevoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nuevo tipo de joyería");

        jComboBox2Nuevo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Elegir tipo", "Anillo", "Pendiente", "Cinturon", "Colgante" }));
        jComboBox2Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2NuevoActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton1ActualizarSinEncantar,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 268,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextField1NombreJoyeriaViejo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                137,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jTextField1NombreJoyeria1Nuevo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                137,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jComboBox2Nuevo, 0,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jComboBox1Viejo, 0,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))))
                                                .addGap(32, 32, 32)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(19, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField1NombreJoyeriaViejo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jComboBox1Viejo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField1NombreJoyeria1Nuevo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jComboBox2Nuevo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51,
                                                        Short.MAX_VALUE)
                                                .addComponent(jButton1ActualizarSinEncantar,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1))
                                .addGap(44, 44, 44)));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1NombreJoyeriaViejoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1NombreJoyeriaViejoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1NombreJoyeriaViejoActionPerformed

    private void jButton1ActualizarSinEncantarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActualizarSinEncantarActionPerformed
        String nombreViejo = jTextField1NombreJoyeriaViejo.getText().toLowerCase();
        String tipoViejo = jComboBox1Viejo.getSelectedItem().toString().toLowerCase();
        String nombreNuevo = jTextField1NombreJoyeria1Nuevo.getText().toLowerCase();
        String tipoNuevo = jComboBox2Nuevo.getSelectedItem().toString().toLowerCase();
        if (nombreViejo.isEmpty() || tipoViejo.isEmpty() || nombreNuevo.isEmpty() || tipoNuevo.isEmpty()) {
            jTextArea1.setText("Los campos no pueden estar vacios.");
        } else {
            JoyeriaSelect.actualizarJoyeriaSinEncantar(nombreViejo, tipoViejo, nombreNuevo, tipoNuevo);
            jTextArea1.setText("Se ha actualizado la joyería de " + nombreViejo + " a " + nombreNuevo);
            menu.EliminarViejo(nombreViejo);
            jTextField1NombreJoyeria1Nuevo.setText("");
            jTextField1NombreJoyeriaViejo.setText("");
        }
    }// GEN-LAST:event_jButton1ActualizarSinEncantarActionPerformed

    private void jTextField1NombreJoyeria1NuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1NombreJoyeria1NuevoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1NombreJoyeria1NuevoActionPerformed

    private void jComboBox1ViejoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ViejoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox1ViejoActionPerformed

    private void jComboBox2NuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2NuevoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBox2NuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ActualizarSinEncantar;
    private javax.swing.JComboBox<String> jComboBox1Viejo;
    private javax.swing.JComboBox<String> jComboBox2Nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1NombreJoyeria1Nuevo;
    private javax.swing.JTextField jTextField1NombreJoyeriaViejo;
    // End of variables declaration//GEN-END:variables
}
