/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iamriven.joyeria;

/**
 *
 * @author Juan Antonio
 */
public class jPanel10removeJoyeria extends javax.swing.JPanel {

        /**
         * Creates new form jPanel10removeJoyeria
         */
        public jPanel10removeJoyeria() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTextField1NombreJoyeria = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jButton1ActualizarSinEncantar = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();

                setName("removejoyeria"); // NOI18N
                setPreferredSize(new java.awt.Dimension(722, 379));

                jTextField1NombreJoyeria.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1NombreJoyeriaActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setText("Eliminar joyería");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("Nombre viejo");

                jButton1ActualizarSinEncantar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jButton1ActualizarSinEncantar.setText("Eliminar joyería");
                jButton1ActualizarSinEncantar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActualizarSinEncantarActionPerformed(evt);
                        }
                });

                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(53, 53, 53)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jButton1ActualizarSinEncantar,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                268,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jTextField1NombreJoyeria,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                137,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addComponent(jLabel3)))
                                                                                                .addGap(38, 38, 38)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                344,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(19, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                50,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(5, 5, 5)
                                                                                                .addComponent(jLabel3)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextField1NombreJoyeria,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                112,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton1ActualizarSinEncantar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                85,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane1))
                                                                .addGap(44, 44, 44)));
        }// </editor-fold>//GEN-END:initComponents

        private void jTextField1NombreJoyeriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1NombreJoyeriaActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextField1NombreJoyeriaActionPerformed

        private void jButton1ActualizarSinEncantarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActualizarSinEncantarActionPerformed
                String nombre = jTextField1NombreJoyeria.getText().toLowerCase();
                if (nombre.isEmpty()) {
                        jTextArea1.setText("Los campos no pueden estar vacios.");
                } else {
                        JoyeriaSelect.eliminarJoyeria(nombre);
                        jTextArea1.setText("Se ha eliminado la joyería correctamente.");
                }
        }// GEN-LAST:event_jButton1ActualizarSinEncantarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1ActualizarSinEncantar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextField jTextField1NombreJoyeria;
        // End of variables declaration//GEN-END:variables
}
