/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iamriven.joyeria;

import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.List;

/**
 *
 * @author Alumnado
 */
public class menu extends javax.swing.JFrame {

    CardLayout cardLayout;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        CargarCombo();
        cardLayout = (CardLayout) JPanelMain.getLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1ActualizarLista = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenuItemAddJoyeria = new javax.swing.JMenuItem();
        jMenuItem1UpdateJoyeriaNormal = new javax.swing.JMenuItem();
        jMenuItem2UpdateJoyeriaEncantada = new javax.swing.JMenuItem();
        jMenuItem1AddStats = new javax.swing.JMenuItem();
        jMenuItem1RemoveStats = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPanelMain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Garmoth 2.0 ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir joyería" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1ActualizarLista.setText("Actualizar lista");
        jButton1ActualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActualizarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(230, 230, 230)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addComponent(jComboBox2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 218,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton1ActualizarLista,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 114,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addContainerGap(17, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1ActualizarLista))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE)));

        JPanelMain.add(jPanel1, "card1");

        jPanel2.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 722, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 380, Short.MAX_VALUE));

        JPanelMain.add(jPanel2, "card2");

        jMenu1.setText("Gestionar");

        jMenuItemInicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemInicio.setText("Inicio");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemInicio);

        jMenuItemAddJoyeria.setText("Añadir joyería");
        jMenuItemAddJoyeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddJoyeriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAddJoyeria);

        jMenuItem1UpdateJoyeriaNormal.setText("Actualizar joyería normal");
        jMenuItem1UpdateJoyeriaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1UpdateJoyeriaNormalActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1UpdateJoyeriaNormal);

        jMenuItem2UpdateJoyeriaEncantada.setText("Actualizar joyería encantada");
        jMenuItem2UpdateJoyeriaEncantada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2UpdateJoyeriaEncantadaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2UpdateJoyeriaEncantada);

        jMenuItem1AddStats.setText("Añadir estadísticas a joyería encantada");
        jMenuItem1AddStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1AddStatsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1AddStats);

        jMenuItem1RemoveStats.setText("Eliminar estadísticas de una joyeria");
        jMenuItem1RemoveStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1RemoveStatsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1RemoveStats);

        jMenuItem1.setText("Eliminar joyería");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel10removeJoyeria removejoyeria = new jPanel10removeJoyeria();
        JPanelMain.add(removejoyeria, "removejoyeria");
        cardLayout.show(JPanelMain, "removejoyeria");
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1RemoveStatsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1RemoveStatsActionPerformed
        jPanel9RemoveStats removestats = new jPanel9RemoveStats();
        JPanelMain.add(removestats, "removestats");
        cardLayout.show(JPanelMain, "removestats");
    }// GEN-LAST:event_jMenuItem1RemoveStatsActionPerformed

    private void jMenuItem1AddStatsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1AddStatsActionPerformed
        jPanel8AddStats AddStats = new jPanel8AddStats();
        JPanelMain.add(AddStats, "addstats");
        cardLayout.show(JPanelMain, "addstats");
    }// GEN-LAST:event_jMenuItem1AddStatsActionPerformed

    private void jButton1ActualizarListaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActualizarListaActionPerformed
        Actualizarcombo();
    }// GEN-LAST:event_jButton1ActualizarListaActionPerformed

    private void jMenuItem1UpdateJoyeriaNormalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1UpdateJoyeriaNormalActionPerformed
        jPanel6Update UpdateSinEncantar = new jPanel6Update();
        JPanelMain.add(UpdateSinEncantar, "updatesinencantar");
        cardLayout.show(JPanelMain, "updatesinencantar");
    }// GEN-LAST:event_jMenuItem1UpdateJoyeriaNormalActionPerformed

    private void jMenuItem2UpdateJoyeriaEncantadaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2UpdateJoyeriaEncantadaActionPerformed
        jPanel7updateEncantada UpdateJoyeriaEncantada = new jPanel7updateEncantada();
        JPanelMain.add(UpdateJoyeriaEncantada, "cardupdateenchanted");
        cardLayout.show(JPanelMain, "cardupdateenchanted");
    }// GEN-LAST:event_jMenuItem2UpdateJoyeriaEncantadaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        String joyeriaSeleccionada = jComboBox2.getSelectedItem().toString().toLowerCase();

        List<Encantados> lista_encantados = JoyeriaSelect.recuperarJoyeriaEncantada(joyeriaSeleccionada);
        StringBuilder sb = new StringBuilder();
        DecimalFormat formato = new DecimalFormat("###,###,###");
        for (Encantados encantado : lista_encantados) {
            String nombre = encantado.getNombre();
            sb.append("Nombre: ").append(nombre.substring(0, 1).toUpperCase() + nombre.substring(1).toLowerCase())
                    .append(", nivel: " + encantado.getNivel())
                    .append(", precio: " + formato.format(encantado.getPrecio()))
                    .append(", precisión: " + encantado.getAccuracy())
                    .append(", evasión: " + encantado.getEvasion() + "\n");
        }

        jTextArea1.setText(sb.toString());
    }

    private void jMenuItemAddJoyeriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemAddJoyeriaActionPerformed
        jPanel5AddJoyeria addusers = new jPanel5AddJoyeria();
        JPanelMain.add(addusers, "cardusers");
        cardLayout.show(JPanelMain, "cardusers");
    }// GEN-LAST:event_jMenuItemAddJoyeriaActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemInicioActionPerformed
        cardLayout.show(JPanelMain, "card1");
    }// GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
    }// GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    public void CargarCombo() {

        List<Joyeria> lista_joyeria = JoyeriaSelect.recuperarJoyeria();
        for (Joyeria joyeria : lista_joyeria) {
            jComboBox2.addItem(joyeria.getNombre().toLowerCase());
        }
    }

    public void Actualizarcombo() {
        List<Joyeria> lista_joyeria = JoyeriaSelect.recuperarJoyeria();
        for (Joyeria joyeria : lista_joyeria) {
            boolean existe = false;
            for (int i = 0; i < jComboBox2.getItemCount(); i++) {
                if (jComboBox2.getItemAt(i).equals(joyeria.getNombre().toLowerCase())) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                jComboBox2.addItem(joyeria.getNombre().toLowerCase());

            }
        }
    }

    public static void EliminarViejo(String nombreViejo) {
        for (int i = 0; i < jComboBox2.getItemCount(); i++) {
            if (jComboBox2.getItemAt(i).equals(nombreViejo)) {
                jComboBox2.removeItemAt(i);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelMain;
    private javax.swing.JButton jButton1ActualizarLista;
    private static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem1AddStats;
    private javax.swing.JMenuItem jMenuItem1RemoveStats;
    private javax.swing.JMenuItem jMenuItem1UpdateJoyeriaNormal;
    private javax.swing.JMenuItem jMenuItem2UpdateJoyeriaEncantada;
    private javax.swing.JMenuItem jMenuItemAddJoyeria;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
